Repository 2025-HERETHON/2025-herethon-2, pull requests merged in 2025-07, with the labels that each got.

#17 [Feat]공통 상단/하단 바 구현
  univerth/static/css/navbar.css
  univerth/static/css/quiz.css
  univerth/static/images/navbar/user-account-basic.svg
  univerth/static/js/main.js
  univerth/static/js/quiz.js
  univerth/templates/navbar.html
Labels: FE, feat

#23 [Feat] 챌린지 목록 조회/ 챌린지 추가
  univerth/challenges/migrations/0005_alter_challenge_participant_num.py
  univerth/challenges/models.py
  univerth/challenges/static/challenges/css/ch_add.css
  univerth/challenges/static/challenges/css/ch_group.css
  univerth/challenges/static/challenges/css/ch_my.css
  univerth/challenges/static/challenges/images/img1.svg
  univerth/challenges/static/challenges/images/img2.svg
  univerth/challenges/static/challenges/images/img3.svg
  univerth/challenges/static/challenges/images/img4.svg
  univerth/challenges/static/challenges/js/ch_add.js
  univerth/challenges/static/challenges/js/ch_group.js
  univerth/challenges/static/challenges/js/ch_my.js
  univerth/challenges/templates/challenges/ch_add.html
  univerth/challenges/templates/challenges/ch_group.html
  univerth/challenges/templates/challenges/ch_my.html
  univerth/challenges/urls.py
  univerth/challenges/views_list.py
  univerth/univerth/urls.py
Labels: BE

#24 [Feat] 홈 페이지 일정별 모달창 기능 추가
  univerth/static/css/home.css
  univerth/static/css/navbar.css
  univerth/static/css/quiz.css
  univerth/static/images/home/callendar_background.png
  univerth/static/js/home.js
  univerth/static/js/quiz.js
  univerth/templates/home.html
  univerth/templates/navbar.html
Labels: FE, feat

#42 [Fix] 홈/퀴즈 페이지 데이터 연동
  univerth/static/css/home.css
  univerth/static/css/navbar.css
  univerth/static/css/quiz.css
  univerth/static/images/navbar/logo_icon.png
  univerth/static/js/home.js
  univerth/static/js/main.js
  univerth/static/js/quiz.js
  univerth/templates/home.html
  univerth/templates/main.html
  univerth/templates/navbar.html
  univerth/templates/quiz.html
Labels: FE, Fix

#48 [Feat] 마이페이지 구현(데이터 연결완료)
  .env
  univerth/myvenv/Scripts/Activate.ps1
  univerth/myvenv/Scripts/activate
  univerth/myvenv/Scripts/activate.bat
  univerth/myvenv/Scripts/django-admin.exe
  univerth/myvenv/Scripts/pip.exe
  univerth/myvenv/Scripts/pip3.exe
  univerth/myvenv/Scripts/python.exe
  univerth/myvenv/Scripts/pythonw.exe
  univerth/myvenv/Scripts/sqlformat.exe
  univerth/myvenv/pyvenv.cfg
  univerth/static/css/mypage.css
  univerth/static/css/quiz.css
  univerth/static/images/navbar/back_icon.png
  univerth/static/js/main.js
  univerth/static/js/mypage.js
  univerth/templates/mypage.html
  univerth/users/views_mypage.py
Labels: FE, feat

#65 [Fix] 누락된 지도 장소 조희 관련 파일 추가 업로드
  univerth/static/css/map.css
  univerth/static/images/map/custom_marker.png
  univerth/static/js/main.js
  univerth/static/js/map.js
Labels: FE, Fix

#80 [FIX] css 수정(4): 맵 장소추가
  univerth/static/css/map_add.css
  univerth/static/css/navbar.css
  univerth/static/js/main.js
  univerth/static/js/map_add.js
  univerth/templates/create_feed.html
  univerth/templates/map_add.html
Labels: FE
